id = "prime-dark"
name = "Prime-dark"
version = "0.0.1"
schema_version = 1
authors = ["Priyanshu"]
description = "A Highly Contrasted dark Theme for Zed"
repository = "https://github.com/priyanshu00001/prime-dark"
